trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright browsers'

  - script: npx playwright test Keka-engage/tests/Survey.spec.ts
    displayName: 'Run only Survey.spec.ts'

  - publish: playwright-report
    artifact: playwright-report
    displayName: 'Publish Playwright HTML report'